# GoGs Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogs-deployment
  labels:
    app: gogs
    owner: Gallian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
  template:
    metadata:
      labels:
        app: gogs
    spec:
      containers:
      - name: gogs
        image: gallianzeon/gogs:latest
        env:
        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: gogs
        - name: DB_USER
          value: gogs
        - name: DB_PASSWD
          value: gogs
        ports:
        - containerPort: 3000
---
# GoGs Service
apiVersion: v1
kind: Service
metadata:
  name: gogs-service
  labels:
    app: gogs
    owner: Gallian
spec:
  selector:
    app: gogs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
# PSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: gogs
    owner: Gallian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: gogs
        - name: POSTGRES_PASSWORD
          value: gogs
        - name: POSTGRES_DB
          value: gogs
        ports:
        - containerPort: 5432
---
# PSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: gogs
    owner: Gallian
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
